### PR TITLE
[SOSSE-5815] DOCO Support App-V deployment

### PR DESCRIPTION
**Pull request by SebastianGodelet**
@ejhinde Add an actual example of a global config.xml file

### CODE REVIEW

**Comment by ejhinde** [comment]
OOOh it works. Thanks @SebastianGodelet

**Comment by SebastianGodelet** [comment]
@ejhinde , did you actually test it?

**Comment by ejhinde** [comment]
@SebastianGodelet  Hmm ok, no I checked it by eye in the GitHub UI.

**Comment by SebastianGodelet** [comment]
@ejhinde yeah IMHO it should be fine. We actually don't have App-V deployment tested here. Something we should do eventually. I just figured we say: the file is easy to be edited, but actually as it doesn't exist by default it is not trivial at all for starters.

**Pull request merged**
