### PR TITLE
remove the code of judge environment

### PR DESCRIPTION
**Pull request by CharlesWang1**
https://toadjira.labs.dell.com/browse/PL-6214

### CODE REVIEW

**Comment by CharlesWang1** [comment]
@chuchuva @GuoxinLiu @CalvinCai Please help me to review the code.

**Comment by CalvinCai** [comment]
Hi, @CharlesWang1 , Why do you remove the environment judgment ?  Is that we need to edit it in test environment ?

**Comment by CharlesWang1** [comment]
@CalvinCai  test environment and product environment all can be edited

**Comment by CalvinCai** [comment]
+1

**Pull request merged**
